/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package ru.clevertec.plugin.release

import spock.lang.Specification
import spock.lang.TempDir

/**
 * A simple functional test for the 'ru.clevertec.plugin.release.greeting' plugin.
 */
class RuClevertecPluginReleasePluginFunctionalTest extends Specification {
    @TempDir
    private File projectDir

    private getBuildFile() {
        new File(projectDir, "build.gradle")
    }

    private getSettingsFile() {
        new File(projectDir, "settings.gradle")
    }

    def "can run task"() {
        given:
        settingsFile << ""
        buildFile << """
plugins {
    id('ru.clevertec.plugin.release')
}
"""

    }
}
