/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package ru.clevertec.plugin.release

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'ru.clevertec.plugin.release.greeting' plugin.
 */
class RuClevertecPluginReleasePluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

    }
}
